# site settings
title: Hi, I'm John Nutter
subtitle: Full stack developer
email: hello@jnutterdev.com
description: I'm a full stack developer with a passion for web technologies
url: "https://www.jnutterdev.com"
baseurl: ""
author: John Nutter

# development settings
host: 0.0.0.0

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9
limit_posts: 5

# social settings
email_addy: hello@jnutterdev.com
500px_url:
facebook_url:
github_url: "&#104;&#101;&#108;&#108;&#111;&#064;&#106;&#110;&#117;&#116;&#116;&#101;&#114;&#100;&#101;&#118;&#046;&#099;&#111;&#109;"
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jnutterdev
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jnutterdev

# build settings
markdown: kramdown

sass:
  style: compressed

# exclude files
exclude:
  - jnutterdev-blog

safe: true
