# site settings
title: Hi, I'm John Nutter
subtitle: Back end developer & Sysadmin
email: hello@jnutterdev.com
description: Back end developer and sysadmin with a passion for Ruby on Rails
url: "https://www.jnutterdev.com"
baseurl: ""
author: John Nutter

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
limit_posts: 5

# social settings
email_addy: hello@jnutterdev.com
500px_url:
facebook_url:
github_url: https://github.com/terribledevice
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/withonlyamap/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/terribledevice

# build settings
markdown: kramdown

sass:
  style: compressed
